<a href="https://colab.research.google.com/github/pulavarthilakshmimeherrishitha/AI-Lab/blob/master/Experiment_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Experiment no:1 - Numpy
###(i) Different ways to create Numpy arrays.

 (a)Creating Numpy arrays using list

In [ ]:
import numpy as np
r = np.array([23,56,73,100])
r

array([ 23,  56,  73, 100])

In [ ]:
r = np.array([[65,78,59],[78,56,93]])
r

array([[65, 78, 59],
       [78, 56, 93]])

(b)Creating numpy arrays using arange

In [ ]:
r = np.arange(44,66,2)
r

array([44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

In [ ]:
r = np.arange(26)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

### (ii) Add,remove,modify elements in an array

(a) Add:

In [ ]:
import numpy as np
r = np.array([65,44,89,45])
p = np.append(r,[66,93,108])
p

array([ 65,  44,  89,  45,  66,  93, 108])

(b) Remove:

In [ ]:
r = np.array([64,108,99,25])
r = np.delete(r,2)
r

array([ 64, 108,  25])

(c) Modify:

In [ ]:
r = np.array([66,52,98,16])
r[3] = 65
r

array([66, 52, 98, 65])

###(iii)Arithematic operations of Numpy array

In [ ]:
 a = np.array( [34,67,89,65,44] )
b = np.arange( 5 )
print(a)
print(b)

[34 67 89 65 44]
[0 1 2 3 4]


In [ ]:
r = a+b
print(r)

[34 68 91 68 48]


In [ ]:
r = a-b
print(r)

[34 66 87 62 40]


In [ ]:
r = a*b
print(r)

[  0  67 178 195 176]


In [ ]:
r = b/a
print(r)

[0.         0.01492537 0.02247191 0.04615385 0.09090909]


In [ ]:
print(a**4)

[ 1336336 20151121 62742241 17850625  3748096]


In [ ]:
print(np.cos(b))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [ ]:
print(a>50)

[False  True  True  True False]


###(iv) Slicing and iterating of Numpy arrays

 
(a) Slicing :

In [ ]:
 a=np.arange(6)**3
print(a)

[  0   1   8  27  64 125]


In [ ]:
 print(a[5])
print(a[4:5])

125
[64]


In [ ]:
a=np.arange(15).reshape(5,3)**3
print(a)

[[   0    1    8]
 [  27   64  125]
 [ 216  343  512]
 [ 729 1000 1331]
 [1728 2197 2744]]


In [ ]:
 print(a[2:5]) 
print(a[2:3,4:5]) 
print(a[4,])
print(a[:3,:2])

[[ 216  343  512]
 [ 729 1000 1331]
 [1728 2197 2744]]
[]
[1728 2197 2744]
[[  0   1]
 [ 27  64]
 [216 343]]


###Slicing using negative index

In [ ]:
a=np.arange(15)
print(a[-4]) 
print(a[-4:-1]) 
print(a[-5:-2])

11
[11 12 13]
[10 11 12]


In [ ]:
a=np.arange(15).reshape(3,5)**3
a

array([[   0,    1,    8,   27,   64],
       [ 125,  216,  343,  512,  729],
       [1000, 1331, 1728, 2197, 2744]])

In [ ]:
 print(a[-2,]) 
print(a[-2,-3]) 
print(a[-3:-1,-2:-1])

[125 216 343 512 729]
343
[[ 27]
 [512]]


(b)Iterating :

In [ ]:
 
a=np.arange(15).reshape(5,3)**3 
print(a)
for i in a:
    print(i)

[[   0    1    8]
 [  27   64  125]
 [ 216  343  512]
 [ 729 1000 1331]
 [1728 2197 2744]]
[0 1 8]
[ 27  64 125]
[216 343 512]
[ 729 1000 1331]
[1728 2197 2744]


In [ ]:
 for i in a.flat:
    print(i)

0
1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744


###(v) Matrix operations on Numpy arrays

In [ ]:
 
import numpy as np
p = np.array([[5,6],[4,5]])
q = np.array([[6,3],[3,6]])
print(p+q)
print(p-q)
print(p@q)
print(p/q)

[[11  9]
 [ 7 11]]
[[-1  3]
 [ 1 -1]]
[[48 51]
 [39 42]]
[[0.83333333 2.        ]
 [1.33333333 0.83333333]]
